version: "3.8"

volumes:
  db_data:
    driver: local

networks:
  db:
    driver: bridge

services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postrgesql/data
      - ./src/main/resources/db/product.csv:/opt/data/product.csv
      - ./src/main/resources/db/size-1.csv:/opt/data/size-1.csv
      - ./src/main/resources/db/stock.csv:/opt/data/stock.csv
    ports:
      - '5432:5432'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    networks:
      - db
